apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cfgmap2
  labels:
  {{- include "parentchart.labels" . | nindent 4 }}
data:
  dessert: {{ .Values.dessert }}
  salad: {{ .Values.global.salad }}
