# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "opensearch-terraform-state-dev"
    dynamodb_table = "opensearch-terraform-state-dev-table"
    key            = "./terraform.tfstate"
    profile        = "singleton"
    region         = "eu-west-3"
  }
}
